"""Signed, expiring magic links for the public pet web view.

A token is an opaque string: `{pet_id}.{expiry_ts}.{hmac}` where the HMAC covers
pet_id + expiry using NOTIFICATION_SECRET. This means the link can only be
generated by the backend and expires, without requiring any login.
"""

import hashlib
import hmac
import time
import uuid

from app.config import get_settings


def _sign(parts: str) -> str:
    return hmac.new(
        get_settings().NOTIFICATION_SECRET.encode("utf-8"),
        parts.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()


def create_pet_token(pet_id: uuid.UUID, ttl_days: int | None = None) -> str:
    settings = get_settings()
    ttl = ttl_days or settings.MAGIC_LINK_TTL_DAYS
    expiry = int(time.time()) + ttl * 86400
    parts = f"{pet_id}.{expiry}"
    return f"{parts}.{_sign(parts)}"


def verify_pet_token(token: str) -> uuid.UUID | None:
    """Return the pet_id if the token is well-formed, signed and unexpired."""
    try:
        pet_part, expiry_part, sig = token.split(".")
        parts = f"{pet_part}.{expiry_part}"
        if not hmac.compare_digest(sig, _sign(parts)):
            return None
        if int(expiry_part) < int(time.time()):
            return None
        return uuid.UUID(pet_part)
    except (ValueError, AttributeError):
        return None
