"""Public, unauthenticated endpoints for magic-link pages.

`GET /public/pet/{token}` returns a minimal, read-only snapshot of a pet's
profile, its most recent visit and bill — only reachable via a signed, expiring
magic link generated by the backend. No login is required; the token itself is
the credential.
"""

import uuid

from fastapi import APIRouter, Depends
from sqlmodel.ext.asyncio.session import AsyncSession
from sqlmodel import select
from app.database import get_session
from app.core.exceptions import NotFoundError
from app.models.pet import Pet
from app.models.owner import Owner
from app.models.appointment import Appointment
from app.models.invoice import Invoice
from app.models.invoice_item import InvoiceItem
from app.models.medical_record import MedicalRecord
from app.services.magic_link import verify_pet_token

router = APIRouter(prefix="/public", tags=["public"])


@router.get("/pet/{token}")
async def public_pet_view(token: str, session: AsyncSession = Depends(get_session)):
    pet_id = verify_pet_token(token)
    if pet_id is None:
        raise NotFoundError("Invalid or expired link")

    pet = await session.get(Pet, pet_id)
    if not pet:
        raise NotFoundError("Pet not found")

    owner = None
    if pet.owner_id:
        owner = await session.get(Owner, pet.owner_id)

    # Most recent appointment + its invoice
    appt_result = await session.execute(
        select(Appointment)
        .where(Appointment.pet_id == pet_id)
        .order_by(Appointment.start_time.desc())
        .limit(1)
    )
    appointment = appt_result.scalar_one_or_none()

    invoice = None
    items = []
    if appointment:
        inv_result = await session.execute(
            select(Invoice).where(Invoice.appointment_id == appointment.id)
        )
        invoice = inv_result.scalar_one_or_none()
        if invoice:
            item_result = await session.execute(
                select(InvoiceItem).where(InvoiceItem.invoice_id == invoice.id)
            )
            items = item_result.scalars().all()

    # Latest few medical records for the timeline
    rec_result = await session.execute(
        select(MedicalRecord)
        .where(MedicalRecord.pet_id == pet_id)
        .order_by(MedicalRecord.recorded_at.desc())
        .limit(5)
    )
    records = rec_result.scalars().all()

    return {
        "pet": {
            "id": str(pet.id),
            "name": pet.name,
            "species": pet.species.value,
            "breed": pet.breed,
            "gender": pet.gender.value,
            "color": pet.color,
            "date_of_birth": str(pet.date_of_birth) if pet.date_of_birth else None,
            "weight_kg": pet.weight_kg,
            "microchip_id": pet.microchip_id,
        },
        "owner": {"first_name": owner.first_name, "last_name": owner.last_name} if owner else None,
        "appointment": {
            "id": str(appointment.id) if appointment else None,
            "reason": appointment.reason if appointment else None,
            "start_time": appointment.start_time.isoformat() if appointment else None,
            "status": appointment.status.value if appointment else None,
        },
        "invoice": {
            "id": str(invoice.id) if invoice else None,
            "total_amount": invoice.total_amount if invoice else None,
            "status": invoice.status.value if invoice else None,
            "items": [
                {
                    "description": i.description,
                    "quantity": i.quantity,
                    "unit_price": i.unit_price,
                    "total_price": i.total_price,
                }
                for i in items
            ],
        } if invoice else None,
        "recent_records": [
            {
                "record_type": r.record_type.value,
                "diagnosis": r.diagnosis,
                "treatment": r.treatment,
                "recorded_at": r.recorded_at.isoformat() if r.recorded_at else None,
            }
            for r in records
        ],
    }
